### ISSUE TITLE
Почему вывод на экран влияет на работу генератора

### ISSUE THREAD

**Issue by YuriyNaumov** [natasha/yargy-examples#3]
Здравствуйте, 

Взял пример из обучающего видео и ноутбука. Прошу подсказать   

Почему если я просто вывожу на экран  значения, формируемые генератором findall он не определяет факт http://joxi.ru/BA0VOXaCwPooXm  а если эти строки закомментировать, то факт определяется. Каким образом функция print/display влияет на работу  генератора http://joxi.ru/VrwZn7piv8ddEA ?

**Comment by kuk** [comment]
Findall возвращает генератор. По генератору можно проитерироваться только один раз. Когда делаете принты генератор оказывается прочитан
